### PR TITLE
Various patches

### PR DESCRIPTION
**Pull request by sim0nx**
Hi,

Thank you for releasing your library!
Here are a bunch of patches I have collected from Rafiot's branch as well as a number of changes I have done (pep8, pep3101, implementations for issue requests on your gitlab etc).

Could you please review them and merge if everything looks good?

Thank you

### CODE REVIEW

**Comment by sim0nx** [comment]
fixes #5 #4 #3 #2 #1

**Comment by e3rd** [comment]
I'm really amazed you implemented all the pending issues, thank you.

**Comment by sim0nx** [comment]
Closes #5 #4 #3 #2 #1

You're welcome, we use the library so we needed those fixes :-)

**Comment by tbooth** [comment]
Great to see continued support for this library :-) - thanks @e3rd and @sim0nx.

**Pull request merged**
