### PR TITLE
Type support

### PR DESCRIPTION
**Pull request by sim0nx**
Hi,

I have added type support to the library. As the code still supports Python2 I have done the typing in a stub file.
As PEP 561 only supports packages, not module-only libraries, I had to do the necessary changes, i.e. create a "rt" folder and move "rt.py" there.
The imports are such that this will not break any current code (tested here).
The library must be PEP 561 compatible for mypy to realise that it contains typing information.

I have done the typing according to the code comments and actual code.

### CODE REVIEW

**Comment by wagner-certat** [comment]
> As the code still supports Python2 I have done the typing in a stub file.

But Python 2 is out of support now anyway.

**Comment by e3rd** [comment]
In my opinion, the compatibility with Python 2 is just a coincidence. And since Python 3.5 is going to end at 2020-09-13 (now it has security fixes only, no bug fixes), I vote for having Python 3.6+ as the least version supported. 

What do you think, guys? If you aggree, would not you be sim0nx so charitable and re-work the pull request with no benevolence to Python2 if that would lead to better code? That means to put the annotations inline and change the smallest supported version to 3.6.

**Comment by sim0nx** [comment]
Perfect, that would have been my next proposal anyway!

If you all I agree, I will work on a new PR to make it inline and the lib PY3 only.

**Comment by e3rd** [comment]
I'd be really glad! :)

**Comment by sim0nx** [comment]
The basic work is done, typing is inline now and I have done a small number of fixes to remove any legacy code.

As this breaks any <PY3 code, I would suggest to bump the library to a new major version, i.e. 2.0.0.

Would you be ok with me adding the following changes as well:
1. remove all the various auth parameters (default_login, default_password, basic_auth, digest_auth) and replace them with a single "http_auth" parameter where the user can supply the required object ?
-> I am using the lib with kerberos which is currently not covered and requires nasty hacking to make it work, and it makes no sense to support every possible auth method. Having a generic parameter would makes things more flexible and easier.

2. Remove "debug_mode" and implement logging via the "logging" module ?

**Comment by wagner-certat** [comment]
> The basic work is done, typing is inline now and I have done a small number of fixes to remove any legacy code.

Very cool, thanks!

> As this breaks any <PY3 code, I would suggest to bump the library to a new major version, i.e. 2.0.0.

+1

>     1. remove all the various auth parameters (default_login, default_password, basic_auth, digest_auth) and replace them with a single "http_auth" parameter where the user can supply the required object ?

If you do so, please with backwards compatibility to not break anyones code unexpectedly. If that will be the only option to pass auth data to the library in the future, warn the lib users with a DeprecationWarning.

>     2. Remove "debug_mode" and implement logging via the "logging" module ?


Yeah, makes sense. The debug mode was always tricky to activate.

**Comment by sim0nx** [comment]
Thanks for your input

> > ```
> > 1. remove all the various auth parameters (default_login, default_password, basic_auth, digest_auth) and replace them with a single "http_auth" parameter where the user can supply the required object ?
> > ```
> 
> If you do so, please with backwards compatibility to not break anyones code unexpectedly. If that will be the only option to pass auth data to the library in the future, warn the lib users with a DeprecationWarning.

Hmm don't you think that cutting a new major release would justify breaking backwards compatibility ? :-)
Of course I would add a big fat note in the README as well as CHANGES about this. Adapting existing code would be trivial, and as we are using a semantic version scheme, I would guess that (in the best case) no one would be upgrading automatically to v2.

If we we can agree on breaking old code I would tend to also cleanup parameter names to respect PEP rules (e.g. instead of Qeue -> queue) while I'm at it.
But we could also do a v2 with warnings and schedule a v3 with a complete cleanup. Both are ok for me (if this is wanted).

> > ```
> > 2. Remove "debug_mode" and implement logging via the "logging" module ?
> > ```
> 
> Yeah, makes sense. The debug mode was always tricky to activate.

done

**Comment by wagner-certat** [comment]
> > > ```
> > > 1. remove all the various auth parameters (default_login, default_password, basic_auth, digest_auth) and replace them with a single "http_auth" parameter where the user can supply the required object ?
> > > ```
> > 
> > 
> > If you do so, please with backwards compatibility to not break anyones code unexpectedly. If that will be the only option to pass auth data to the library in the future, warn the lib users with a DeprecationWarning.
> 
> Hmm don't you think that cutting a new major release would justify breaking backwards compatibility ? :-)
> Of course I would add a big fat note in the README as well as CHANGES about this. Adapting existing code would be trivial, and as we are using a semantic version scheme, I would guess that (in the best case) no one would be upgrading automatically to v2.
> 
> If we we can agree on breaking old code I would tend to also cleanup parameter names to respect PEP rules (e.g. instead of Qeue -> queue) while I'm at it.
> But we could also do a v2 with warnings and schedule a v3 with a complete cleanup. Both are ok for me (if this is wanted).

I would not release two major versions.

Semantic versioning provides a good scheme for depractions. Citing https://semver.org/#how-should-i-handle-deprecating-functionality

> How should I handle deprecating functionality?

> Deprecating existing functionality is a normal part of software development and is often required to make forward progress. When you deprecate part of your public API, you should do two things: (1) update your documentation to let users know about the change, (2) issue a new minor release with the deprecation in place. Before you completely remove the functionality in a new major release there should be at least one minor release that contains the deprecation so that users can smoothly transition to the new API.

**Comment by sim0nx** [comment]
> > > > ```
> > > > 1. remove all the various auth parameters (default_login, default_password, basic_auth, digest_auth) and replace them with a single "http_auth" parameter where the user can supply the required object ?
> > > > ```
> > > 
> > > 
> > > If you do so, please with backwards compatibility to not break anyones code unexpectedly. If that will be the only option to pass auth data to the library in the future, warn the lib users with a DeprecationWarning.
> > 
> > 
> > Hmm don't you think that cutting a new major release would justify breaking backwards compatibility ? :-)
> > Of course I would add a big fat note in the README as well as CHANGES about this. Adapting existing code would be trivial, and as we are using a semantic version scheme, I would guess that (in the best case) no one would be upgrading automatically to v2.
> > If we we can agree on breaking old code I would tend to also cleanup parameter names to respect PEP rules (e.g. instead of Qeue -> queue) while I'm at it.
> > But we could also do a v2 with warnings and schedule a v3 with a complete cleanup. Both are ok for me (if this is wanted).
> 
> I would not release two major versions.
> 
> Semantic versioning provides a good scheme for depractions. Citing https://semver.org/#how-should-i-handle-deprecating-functionality



I fully agree with you here.
But I am unsure about how to proceed 

I think we both agree that going Py3-only requires a new major version.

I could make a new PR with a minor update and add the deprecation
warnings there, and then merge this PR with a new major where the
changes are applied.

i.e. a 1.0.13 with the deprecation warnings and a 2.0.0 with the
breaking changes.


Would you be ok with that or what is your suggestion ?

**Comment by sim0nx** [comment]
I have made a second PR #46 to mark the mentioned parameters as deprecated.
I did not do it for default_login / default_password as this seems to be used for people who do not use external_auth.

**Comment by e3rd** [comment]
Amazing work, thanks! Last question – do I get it right that I issue #46 as `1.0.13` and then I merge that #45 and issue it as `2.0.0`?

**Comment by sim0nx** [comment]
> Amazing work, thanks! Last question – do I get it right that I issue #46 as `1.0.13` and then I merge that #45 and issue it as `2.0.0`?

Thank you :-)
No please only merge #46 for the moment. Once that is done, I will rebase this branch onto master, do a quick review and remove the "WIP" prefix when done.
I will probably get to that tomorrow

**Comment by e3rd** [comment]
Okay, #46 merged!

**Comment by sim0nx** [comment]
For me this is ready to be merged.
I have added a warning to the readme, updated changes and fixed "docs".

As the docs cleanly build, I would suggest to add this project @ https://readthedocs.org and link the generated docs with a badge in the readme (you have to do this).

**Comment by sim0nx** [comment]
fixes #44

**Comment by e3rd** [comment]
Thank you guys, we released the version 2.0.0 here and on PyPi.
And thanks for the hint with the docs, it looks awesome now!

**Comment by sim0nx** [comment]
It does indeed, great!, thank you for merging my changes!

**Pull request merged**
