### PR TITLE
Add numerical_id to get_ticket resut, fixes #24

### LINKED ISSUE #24: Return numeric ticket id from tracker.search?
Hi! First thing that puzzled me with this library was that the ids returned from the search method is on the form "ticket/{numeric id}", so they cannot be passed directly to other methods like this:

```python

for ticket in tracker.search(...):
    tracker.get_attachments(ticket['id'])
```

Wouldn't it be nice if they could? What is the reason for including the "ticket/" prefix?

### PR DESCRIPTION
**Pull request by vinzBad**
Fix for issue #24

### CODE REVIEW

**Comment by vinzBad** [comment]
reopen to retrigger travis build (changed language of administrateur and support account in Demo-RT to english)

**Comment by vinzBad** [comment]
Hi @iamleot,
No problem, Hacktoberfest is a great motivation :) I've totally missed the other cases...

**Comment by iamleot** [comment]
Vinzenz Sinapius writes:
> Hi @iamleot,
> No problem, Hacktoberfest is a great motivation :) I've totally missed the other cases...

Thank you! :)

**Comment by e3rd** [comment]
Seems awesome, thanks for both PRs!

**Pull request merged**
